number = @{ ASCII_DIGIT+ }
base   = { "i" | "j" | "k" }
term   = { number ~ base | number | base }
quaternion = { sign? ~ term ~ (sign ~ term)* }

vector_in = { quaternion ~ ( "," ~ quaternion)* }
vector = {"[" ~ vector_in ~ "]" }
matrix_in = { vector ~ ("," ~ vector)* }
matrix = {"[" ~ matrix_in ~ "]" }

binary_expr = { sign? ~ matrix ~ op ~ matrix }
expr = { SOI ~ binary_expr ~ EOI }
sign = { "+" | "-" }
op   = { "+" | "-" }
WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
